import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import crypto from 'node:crypto'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PACKAGE_ROOT = path.resolve(__dirname, '..', '..')
const MONOREPO_ROOT = path.resolve(PACKAGE_ROOT, '../..')

export async function createProjectStructure(config) {
  const targetDir = path.join(process.cwd(), config.projectName)

  const exists = await fs
    .access(targetDir)
    .then(() => true)
    .catch(() => false)
  if (exists) {
    throw new Error(`Directory "${config.projectName}" already exists.`)
  }

  await fs.mkdir(path.join(targetDir, 'app', 'models'), { recursive: true })
  await fs.mkdir(path.join(targetDir, 'app', 'controllers'), {
    recursive: true,
  })
  await fs.mkdir(path.join(targetDir, 'app', 'Features'), { recursive: true })
  await fs.mkdir(path.join(targetDir, 'app', 'pages'), { recursive: true })
  await fs.mkdir(path.join(targetDir, 'database', 'migrations'), {
    recursive: true,
  })
  await fs.mkdir(path.join(targetDir, 'public'), { recursive: true })

  await fs.mkdir(path.join(targetDir, 'app', 'routes'), { recursive: true })
  await fs.writeFile(
    path.join(targetDir, 'app', 'routes', 'web.js'),
    `export async function routes(router) {\n  // router.use(someMiddleware)\n  // router.get('/health', (req, res) => res.json({ ok: true }))\n}\n`,
  )

  await fs.mkdir(path.join(targetDir, 'app', 'useApi'), { recursive: true })
  await fs.writeFile(
    path.join(targetDir, 'app', 'useApi', 'getApi.js'),
    `export const getApi = (table) => useApi(\`/api/\${table}\`)\n`,
  )
  await fs.writeFile(
    path.join(targetDir, 'app', 'useApi', 'postApi.js'),
    `export const postApi = (table, data) => useApi(\`/api/\${table}\`, { method: 'POST', body: data })\n`,
  )
  await fs.writeFile(
    path.join(targetDir, 'app', 'useApi', 'putApi.js'),
    `export const putApi = (table, id, data) => useApi(\`/api/\${table}/\${id}\`, { method: 'PUT', body: data })\n`,
  )
  await fs.writeFile(
    path.join(targetDir, 'app', 'useApi', 'deleteApi.js'),
    `export const deleteApi = (table, id) => useApi(\`/api/\${table}/\${id}\`, { method: 'DELETE' })\n`,
  )

  await fs.writeFile(
    path.join(targetDir, '.env'),
    `PORT=3000\nAUTH_SECRET=${crypto.randomUUID()}\nDATABASE_DRIVER=${config.database.driver ?? config.database}\n`,
  )
  await fs.writeFile(
    path.join(targetDir, '.env.example'),
    `PORT=3000\nAUTH_SECRET=\nDATABASE_DRIVER=sqlite\n`,
  )

  await fs.writeFile(
    path.join(targetDir, 'app', 'schedule.js'),
    `export async function schedule(scheduler) {\n  // scheduler.daily('03:00', async () => { /* cleanup */ })\n  // scheduler.every('5m', async () => { /* poll */ })\n}\n`,
  )

  await fs.writeFile(
    path.join(
      targetDir,
      'database',
      'migrations',
      `${Date.now()}_create_jobs_table.js`,
    ),
    `/**\n * Generated by Tylix\n *\n * Generator: MigrationGenerator\n * Version: 0.1.0\n * Feature: Job\n *\n * Do not edit this section.\n */\n\nexport const up = async (schema) => {\n    await schema.createTable("jobs", (table) => {\n        table.increments("id");\n        table.string("job");\n        table.text("payload");\n        table.string("status");\n        table.integer("attempts");\n        table.text("error");\n        table.timestamps();\n    });\n};\n\nexport const down = async (schema) => {\n    await schema.dropTable("jobs");\n};\n`,
  )

  await fs.writeFile(
    path.join(
      targetDir,
      'database',
      'migrations',
      `${Date.now() + 1}_create_cache_table.js`,
    ),
    `/**\n * Generated by Tylix\n *\n * Generator: MigrationGenerator\n * Version: 0.1.0\n * Feature: Cache\n *\n * Do not edit this section.\n */\n\nexport const up = async (schema) => {\n    await schema.createTable("cache", (table) => {\n        table.increments("id");\n        table.string("key").unique();\n        table.text("value");\n        table.datetime("expires_at");\n        table.timestamps();\n    });\n};\n\nexport const down = async (schema) => {\n    await schema.dropTable("cache");\n};\n`,
  )

  await fs.mkdir(path.join(targetDir, 'app', 'jobs'), { recursive: true })
  await fs.writeFile(
    path.join(targetDir, 'app', 'jobs', 'SendWelcomeEmail.js'),
    `export const SendWelcomeEmail = {\n  async handle(payload) {\n    // payload.userId, etc.\n  },\n}\n`,
  )

  await fs.mkdir(path.join(targetDir, 'app', 'seeders'), { recursive: true })
  await fs.writeFile(
    path.join(targetDir, 'app', 'seeders', 'DatabaseSeeder.js'),
    `export async function seed() {\n  // e.g.:\n  // await Post.create({ title: 'First post', body: '...' })\n}\n`,
  )

  const dependencies = {
    '@tylix/cli': `file:${path.join(MONOREPO_ROOT, 'packages', 'cli')}`,
    '@tylix/core': `file:${path.join(MONOREPO_ROOT, 'packages', 'core')}`,
    '@tylix/compiler': `file:${path.join(MONOREPO_ROOT, 'packages', 'compiler')}`,
    '@tylix/generator': `file:${path.join(MONOREPO_ROOT, 'packages', 'generator')}`,
    '@tylix/orm': `file:${path.join(MONOREPO_ROOT, 'packages', 'orm')}`,
    '@tylix/shared': `file:${path.join(MONOREPO_ROOT, 'packages', 'shared')}`,
  }
  if (config.authEnabled) {
    dependencies['@tylix/auth'] =
      `file:${path.join(MONOREPO_ROOT, 'packages', 'auth')}`
  }

  const devDependencies = {}
  if (config.styling === 'tailwind') {
    Object.assign(devDependencies, {
      tailwindcss: '^3.4.0',
      postcss: '^8.4.0',
      autoprefixer: '^10.4.0',
    })
  } else if (config.styling === 'sass') {
    devDependencies.sass = '^1.77.0'
  }

  const scripts = {
    dev: 'tylix dev',
    migrate: 'tylix migrate',
  }
  if (config.styling === 'tailwind') {
    scripts['css:build'] =
      'tailwindcss -i ./app/tailwind-input.css -o ./public/tailwind.css'
    scripts['css:watch'] =
      'tailwindcss -i ./app/tailwind-input.css -o ./public/tailwind.css --watch'
  }

  const packageJson = {
    name: config.projectName,
    version: '0.1.0',
    type: 'module',
    scripts,
    dependencies,
    devDependencies,
  }

  await fs.writeFile(
    path.join(targetDir, 'package.json'),
    JSON.stringify(packageJson, null, 2),
  )

  const gitignoreTemplate = await fs.readFile(
    path.join(PACKAGE_ROOT, 'src', 'templates', 'gitignore.template'),
    'utf-8',
  )
  await fs.writeFile(path.join(targetDir, '.gitignore'), gitignoreTemplate)

  await fs.copyFile(
    path.join(PACKAGE_ROOT, 'assets', 'logo-mark.png'),
    path.join(targetDir, 'public', 'logo-mark.png'),
  )
  await fs.copyFile(
    path.join(PACKAGE_ROOT, 'assets', 'logo-full.png'),
    path.join(targetDir, 'public', 'logo-full.png'),
  )

  return targetDir
}
